### PR TITLE
Dockerfile: fix BASE_IMAGE

### PR DESCRIPTION
**Pull request by Jakob-Koschel**
The `BASE_IMAGE` required for panda includes an underscore while the `BASE_IMAGE` for the docker container requires a colon.

Tried a few things to not have it as two definitions but failed with `sh` and `Dockerfile`.

### CODE REVIEW

**Comment by FlorentRevest** [comment]
Ah snap, this is something that changed  recently in upstream Panda https://github.com/panda-re/panda/commit/476e6e0fab09a5e1b8d5590ff63315cb4b9354aa

Most of the syz-rrr Dockerfile is derived from the panda Dockerfile, I think it would be better to keep them somewhat in sync so it is easy to get their improvements. For example we're also missing https://github.com/panda-re/panda/commit/a502c1f69fb65722d7215a3ab707d8489aedbf65 or https://github.com/panda-re/panda/commit/381301411f110b9a4df3335526f52d78f6702413

Your change per-se looks good but could you rebase these changes instead ?

Alternatively, I wonder if there's a good way to base our Dockerfile on theirs, even though we use a different base ubuntu version :/

**Comment by Jakob-Koschel** [comment]
aha! I didn't realize this part was from upstream panda as well, let me make it closer to their latest version then

**Comment by Jakob-Koschel** [comment]
Alright, I just took all the new changes from the panda-re upstream to fix it. I'm unsure if there is an easy way to keep it automatically up-to-date :/

**Comment by FlorentRevest** [comment]
Thank you!

**Pull request merged**
